import Head from "next/head";
import { Button } from "primereact/button";
import Navbar from "../components/navbar";

import "primereact/resources/themes/lara-light-indigo/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Link Preview Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Navbar />
      </body>
    </div>
  );
}
