import Head from "next/head";
import { Button } from "primereact/button";

import "primereact/resources/themes/lara-light-indigo/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Link Preview Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <div className="my-2">
          <Button label="Click Me 👋🏻" className="!mx-6" />
          <Button label="Click Me One more time 👋🏻" />
        </div>
      </body>
    </div>
  );
}
