import Head from "next/head";
import Navbar from "../components/navbar";
import { InputText } from "primereact/inputtext";
import { Button } from "primereact/button";
import { Toast } from "primereact/toast";
import Tabs from "../components/tabs";
import { useState, useRef } from "react";

import "primereact/resources/themes/lara-light-indigo/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";

export default function Home() {
  const [url, setURL] = useState("");
  const [data, setData] = useState();
  const [isLoading, setIsLoading] = useState(false);
  const toastRef = useRef();

  const submit = async () => {
    if (!url) {
      toastRef.current.show({
        severity: "info",
        summary: "Please provide URL",
      });
      return;
    }
    setIsLoading(true);
    try {
      const res = await fetch(`/api/getPreview?url=${url}`);
      const data = await res.json();
      setIsLoading(false);

      if (data.error) {
        toastRef.current.show({
          severity: "error",
          summary: "Invalid URL",
          detail: "Please enter a valid URL!",
        });
      } else {
        setData(data);
      }
    } catch (err) {
      setIsLoading(false);
      toastRef.current.show({
        severity: "error",
        summary: "Error Message",
        detail: "Preview not available!",
      });
      console.log(err);
    }
  };

  return (
    <div>
      <Head>
        <title>Link Preview Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="bg-[rgb(236,238,248)] h-screen">
        <Navbar />
        <Toast ref={toastRef} />
        <div className="mt-[7rem]">
          <h1 className="text-3xl lg:text-5xl text-slate-800 font-bold text-center !leading-[1.3]">
            Link 🔗 Preview <br /> Generator ⚡
          </h1>
          <div className="flex flex-col lg:flex-row justify-center align items-center my-8 bg-white p-4 rounded-md w-min mx-auto shadow-md">
            <InputText
              value={url}
              onChange={(e) => setURL(e.target.value)}
              placeholder="Enter URL"
              className="w-auto lg:w-[350px] !mx-5 !my-4 lg:my-0"
            />
            <Button
              loading={isLoading}
              onClick={submit}
              label={`${isLoading ? "Generating ⌛" : "Submit"}`}
              icon="pi pi-check"
              className={`${isLoading ? "w-[200px]" : ""}`}
            />
          </div>
          <p className="text-center font-bold text-slate-500">
            Link preview will appear here 👇🏻
          </p>
          {data ? <Tabs data={data} /> : <></>}
        </div>
      </body>
    </div>
  );
}
